#### 1.Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files.
* Delete the found duplicate file.
                 * [Hint: use hashlib]
 

In [ ]:
import os
path_p = input("Enter your path :")
files_list = os.listdir(path = path_p)
files_list

In [ ]:
import hashlib
list1=[]          
for i in files_list:
    file_obj=open(path_p+i,'r')
    content=file_obj.read()
    file_obj.close()
    encode_content=content.encode()
    list1.append(hashlib.sha256(encode_content).hexdigest())

In [ ]:
new_dic =dict(zip(files_list,list1))
new_dic

In [ ]:
for i in new_dic:
    file_path=i
    abc_path = os.path.join(path_p,file_path)
    print(abc_path)

In [ ]:
for i in new_dic:
    file_path=i
    abc_path = os.path.join(path_p,file_path)
    os.remove(abc_path)
os.listdir(path_p)

#### 2.Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.Using these packages [random, strings]


In [7]:
import random
import string

def gp():

    ucase = string.ascii_uppercase
    lcase = string.ascii_lowercase
    digits = string.digits
    special = string.punctuation
    
    
    uchars = random.sample(ucase, 1)   # This function takes the list and number of char to get
    lchars = random.sample(lcase, 2)
    dchars = random.sample(digits, 2)
    schars = random.sample(special, 1)

    password_chars = uchars + lchars + dchars +schars
    random.shuffle(password_chars)
    # Convert the characters to a string and return the password
    password = ''.join(password_chars)
    return password
gp()

'>Fpe65'

#### 3.Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [8]:
import sympy
import numpy as np
arr=np.zeros((5,5),dtype='int')

c=1
for i in range (5):
    for j in range (5):
        if sympy.isprime(c):
            arr[i][j]=c**3
        else:
            arr[i][j]=c
        c+=1
print(arr)

[[    1     8    27     4   125]
 [    6   343     8     9    10]
 [ 1331    12  2197    14    15]
 [   16  4913    18  6859    20]
 [   21    22 12167    24    25]]


#### 4.Python program to get the sum of every cubed value and its previous integer. 

In [10]:
arr=np.arange(1,26)
for i in range(len(arr)):
    if sympy.isprime(i+1):
        arr[i]=(i+1)**3+arr[i-1];
ans=arr.reshape(5,5)
        
print(ans)      


[[    1     9    36     4   129]
 [    6   349     8     9    10]
 [ 1341    12  2209    14    15]
 [   16  4929    18  6877    20]
 [   21    22 12189    24    25]]


#### 5.Given two arrays, find their intersection. Examples:

#### Input:  arr1[] = [1, 3, 4, 5, 7]          arr2[] = [2, 3, 5, 6]


In [12]:
#Using frozenset
arr1 = [1, 3, 4, 5, 7]
arr2 = [2, 3, 5, 6]
A=frozenset(arr1)
B=frozenset(arr2)
A.intersection(B)


frozenset({3, 5})

In [16]:
#Using numpy
arr2=np.array([1,3,4,5,7])
arr3=np.array([2,3,5,6])
intersection1=np.intersect1d(arr2,arr3)
print(intersection1)

[3 5]


#### 6.Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [18]:
import numpy as np
arr = np.arange(1, 50) * 7
arr = arr.reshape((7, 7))

lastele = arr[-1][-1]

print(arr)
print("Last element:", lastele)

[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]
Last element: 343


#### 7.	Checker Board Patten using Numpy:
 #### [  1   0   1   0   1   0   1
 ####    0   1   0   1   0   1   0
  ####  1   0   1   0   1   0   1
  ####  0   1   0   1   0   1   0
  ####  1   0   1   0   1   0   1 ]


In [27]:
import numpy as np

x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 8.Create a given Matrix:
* [  A,     B,     C,       D
*  E,      F,     G,       H
*  I,      a,      K,       L
*  M,    N,     o,       P
*  Q,     R,      S,       T
*  U,     0,     W,      O ]

#### Replace all the vowels by np.nan
#### A, E, I, O U  -- >  np.nan
#### Return the count of the missing values


In [4]:
import numpy as np
arr=np.array(list('abcdefghijklmnop'))
print(arr)

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p']


In [6]:
arr1=arr.reshape(4,4)
print(arr1)

[['a' 'b' 'c' 'd']
 ['e' 'f' 'g' 'h']
 ['i' 'j' 'k' 'l']
 ['m' 'n' 'o' 'p']]


In [7]:
c=0
list1=['a', 'e', 'i', 'o', 'u']
for i in range (4):
    for j in range (4):
        if arr1[i][j] in list1:
            c+=1
            arr1[i][j]= np.nan
            
            
print(arr1)
print("Count of missing values is ",c)

[['n' 'b' 'c' 'd']
 ['n' 'f' 'g' 'h']
 ['n' 'j' 'k' 'l']
 ['m' 'n' 'n' 'p']]
Count of missing values is  4
